-- ---------------------------------
-- 1. FATURAMENTO DO MÊS ATUAL
-- --------------------------------
-- SELECT DATA_VENDA,QUANTIDADE_VENDIDA,STATUS_PGTO FROM VENDAS WHERE STATUS_PGTO = 'Pago'AND DATA_VENDA LIKE '2026-03%';

-- SELECT SUM(QUANTIDADE_VENDIDA * SELECT * FROM) AS TOTAL_SOMA FROM VENDAS
 -- WHERE STATUS_PGTO LIKE 'Pag%' AND DATA_VENDA LIKE '2026-03%';

SELECT 
    SUM((P.PRECO_VENDA - P.PRECO_CUSTO) * V.QUANTIDADE_VENDIDA) AS LUCRO_GERAL_ACUMULADO
FROM VENDAS V
JOIN PRODUTOS P ON V.ID_PRODUTO = P.ID_PRODUTO;

-- -------------------------------------------------------
-- 2. LUCRO DO ÚLTIMO MÊS
-- -------------------------------------------------------
SELECT 
    SUM((P.PRECO_VENDA - P.PRECO_CUSTO) * V.QUANTIDADE_VENDIDA) AS LUCRO_GERAL_ACUMULADO
FROM VENDAS V 
JOIN PRODUTOS P ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE STATUS_PGTO LIKE 'Pag%' AND DATA_VENDA LIKE '2026-03%';

-- -------------------------------------
-- 3. LUCRO DOS ÚLTIMOS 3 MESES
-- ------------------------------------

SELECT 
    SUM((P.PRECO_VENDA - P.PRECO_CUSTO) * V.QUANTIDADE_VENDIDA) AS LUCRO_GERAL_ACUMULADO
FROM VENDAS V 
JOIN PRODUTOS P ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE DATA_VENDA LIKE '2026-01%' OR '2026-02%' OR '2026-03%';

-- ----------------------------------
-- PRODUTO MAIS VENDIDO
-- ----------------------------------



