USE DB_T2_ANDRE_HENRIQUE; 

--  CRIAÇÃO DA TABELA FUNCIONÁRIOS -- 
CREATE TABLE IF NOT EXISTS FUNCIONARIOS (

  ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT,
  NOME_FUNCIONARIO VARCHAR(50) NOT NULL,
  SALARIO DECIMAL(10,2) NOT NULL,
  ANO_ENTRADA YEAR NOT NULL,
  CARGO VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_FUNCIONARIO)
  
) ENGINE = InnoDB;
  
--  CRIAÇÃO DA TABELA FORNECEDORES -- 
CREATE TABLE IF NOT EXISTS FORNECEDORES (

  ID_FORNECEDOR INT NOT NULL AUTO_INCREMENT,
  NOME_FORNECEDOR VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_FORNECEDOR)
  
) ENGINE = InnoDB;

--  CRIAÇÃO DA TABELA PRODUTOS -- 
CREATE TABLE IF NOT EXISTS PRODUTOS (

  ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
  NOME_PRODUTO VARCHAR(50) NOT NULL,
  PRECO_VENDA DECIMAL(10,2) NOT NULL,
  PRECO_CUSTO DECIMAL(10,2) NOT NULL,
  ID_FORNECEDOR INT NULL,
  PRIMARY KEY (ID_PRODUTO)

) ENGINE = InnoDB;

--  CRIAÇÃO DA TABELA CLIENTES -- 
CREATE TABLE IF NOT EXISTS CLIENTES (

  ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
  NOME_CLIENTE VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_CLIENTE)

) ENGINE = InnoDB;

--  CRIAÇÃO DA TABELA CLIENTES -- 
CREATE TABLE IF NOT EXISTS VENDAS (
  ID_VENDA INT NOT NULL AUTO_INCREMENT,
  DATA_VENDA DATE NOT NULL,
  ID_PRODUTO INT NOT NULL,
  ID_FUNCIONARIO INT NULL,
  ID_CLIENTE INT NULL,
  QUANTIDADE_VENDIDA INT NOT NULL,
  STATUS_PGTO VARCHAR(10) NOT NULL,
  PRIMARY KEY (ID_VENDA)
  
) ENGINE = InnoDB;